## Задание 1. Создание и изменение массивов

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9.
Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [68]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
A=A*2
for i in range(3):
    for j in range(3):
        if (A[i][j]>10):
            A[i][j]=0
A

array([[ 2,  4,  6],
       [ 8, 10,  0],
       [ 0,  0,  0]])

## Задание 2. Работа с булевыми масками

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.

In [190]:
A = np.random.randint(1, 101, size=(20))
print("Исходный массив: ",A)
print("Числа, которые делятся на 5 без остатка:")
for i in range(20):
    if (A[i]%5==0):
        print(A[i])
        A[i]=-1
print("Массив, в котором элементы, которые делятся на 5 без остатка, заменены на -1: ",A)


Исходный массив:  [18  6 22 88  3 50 42 15 94 47 67 75 19 40 72 78 59 91 32 80]
Числа, которые делятся на 5 без остатка:
50
15
75
40
80
Массив, в котором элементы, которые делятся на 5 без остатка, заменены на -1:  [18  6 22 88  3 -1 42 -1 94 47 67 -1 19 -1 72 78 59 91 32 -1]


## Задание 3. Объединение и разбиение массивов.

Создайте два массива NumPy размером 1×5, заполненные случайными числамиот 0 до 50.

    • Объедините эти массивы в один двумерный массив (по строкам).
    • Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

Выведите все промежуточные и итоговые результаты

In [234]:
A = np.random.randint(0,51, size=(1,5))
B = np.random.randint(0,51, size=(1,5))
print("Массивы 1x5, заполненные случайными числами от 0 до 50:")
print("А =",A);print("B =", B)
matrix = np.vstack((A,B))
print("Массивы А и В, обьединенные в один двумерный массив: ")
print(matrix)
A_new, B_new = np.vsplit(matrix, 2)
print("Двумерный массив, который был разделен обратно на два массива: ")
print("А =",A_new);print("B =", B_new)

Массивы 1x5, заполненные случайными числами от 0 до 50:
А = [[25 19 42 35 15]]
B = [[ 8  7 14 32 35]]
Массивы А и В, обьединенные в один двумерный массив: 
[[25 19 42 35 15]
 [ 8  7 14 32 35]]
Двумерный массив, который был разделен обратно на два массива: 
А = [[25 19 42 35 15]]
B = [[ 8  7 14 32 35]]


## Задание 4. Генерация и работа с линейными последовательностями

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты.

In [286]:
A = np.linspace(-10, 10, 50)
C = np.sum(A)
print("Массив из 50 чисел, равномерно распределенных от -10 до 10:\n", A)
print("Сумма всех элементов массива: ", C)
B = np.sum(A[A>0])
print("Сумма всех положительных элементов массива: ", B)
D = np.sum(A[A<0])
print("Сумма всех отрицательных элементов массива: ", D)

Массив из 50 чисел, равномерно распределенных от -10 до 10:
 [-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]
Сумма всех элементов массива:  7.105427357601002e-15
Сумма всех положительных элементов массива:  127.55102040816328
Сумма всех отрицательных элементов массива:  -127.55102040816327


## Задание 5. Работа с диагональными и единичными матрицами

Создайте:

    • Единичную матрицу размером 4х4.
    • Диагональную матрицу размером 4х4 с диагональными элементами (5,10,15,20), не используя циклы.

Найдите сумму всех элементов каждой из этих матриц и сравните результаты

In [314]:
A = np.eye(4)
print("Единичная матрица размером 4 порядка:\n",A)
B = np.diag([5, 10, 15, 20])
print("Диагональная матрица 4 порядка с диагональными элементами (5,10,15,20):\n", B)
k = np.sum(A)
k1 = np.sum(B)
print("Сумма всех элементов единичной матрицы:",k)
print("Сумма всех элементов диагональной матрицы:",k1)

Единичная матрица размером 4 порядка:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица 4 порядка с диагональными элементами (5,10,15,20):
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма всех элементов единичной матрицы: 4.0
Сумма всех элементов диагональной матрицы: 50


## Задание 6. Создание и базовые операции с матрицами

Создайте две квадратные матрицы NumPy размером 3х3, заполненые случайными целыми числами от 1 до 20. Вычислите и выведите:

    • Их сумму
    • Их разность
    • Их поэлементное произведение

In [356]:
A = np.random.randint(1,21, size=(3,3))
B = np.random.randint(1,21, size=(3,3))
print("A = \n",A)
print("B = \n",B)
C = A + B
print("A + B =\n",C)
D = A - B
print("A - B =\n",D)
E = A*B
print("A * B (поэлементное произведение) =\n",E)

A = 
 [[ 8 15 16]
 [ 6 12  9]
 [16 17 14]]
B = 
 [[ 1 13 14]
 [ 2  8 11]
 [19 18 17]]
A + B =
 [[ 9 28 30]
 [ 8 20 20]
 [35 35 31]]
A - B =
 [[ 7  2  2]
 [ 4  4 -2]
 [-3 -1 -3]]
A * B (поэлементное произведение) =
 [[  8 195 224]
 [ 12  96  99]
 [304 306 238]]


## Задание 7. Умножение матриц

Создайте две матрицы NumPy:

    • Первую размером 2х3, заполненную случайными числами от 1 до 10.
    • Вторую размеров 3х2, заполненную случайными числами от 1 до 10.

Выполните матричное умножение и выведите результат.

In [362]:
A = np.random.randint(1,11, size=(2,3))
B = np.random.randint(1,11, size=(3,2))
print("A = \n",A)
print("B = \n",B)
C = np.dot(A,B)
print("Произведение матрицы A на матрицу B:\n",C)

A = 
 [[ 5  7  4]
 [ 8  3 10]]
B = 
 [[9 8]
 [8 2]
 [5 2]]
Произведение матрицы A на матрицу B:
 [[121  62]
 [146  90]]


## Задание 8. Определитель и обратная матрица

Создайте случайную квадратную матрицу 3х3. Найдите и выведите:

    • Определитель этой матрицы
    • Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)

Используйте функции np.linalg.det и np.linalg.inv

In [469]:
A = np.random.rand(3, 3)
print("Матрица А =\n",A)
C = np.linalg.det(A)
print("det A = ", C)
D = np.linalg.inv(A)
if (C != 0):
    print("A⁻¹ = \n", D)
else:
    print("det A = 0, обратной матрицы не существует!")


Матрица А =
 [[0.50650186 0.62886753 0.07887878]
 [0.20213945 0.65439707 0.82874358]
 [0.77868256 0.71258994 0.17992485]]
det A =  0.11464172628121103
A⁻¹ = 
 [[-4.12425788 -0.49668365  4.09582006]
 [ 5.31183787  0.25916168 -3.52241429]
 [-3.18841194  1.12315165  1.78237372]]


## Задание 9. Транспонирование и след матрицы

Создайте матрицу NumPy размером 4х4, содержащую случайные целые числа от 1 до 50. Выведите:

    • Исходную матрицу
    • Транспонированную матрицу
    • След матрицы (сумму элементов на главной диагонали)

Используйте np.trace для нахождения следа.

In [486]:
A = np.random.randint(1,51, size=(4,4))
print("Исходная матрица: \n",A)
print("Транспонированная матрица: \n", np.transpose(A))
print("След матрицы: ", np.trace(A))

Исходная матрица: 
 [[47  5  3  6]
 [ 9 50 32 30]
 [41 46  4  7]
 [29 20 15 44]]
Транспонированная матрица: 
 [[47  9 41 29]
 [ 5 50 46 20]
 [ 3 32  4 15]
 [ 6 30  7 44]]
След матрицы:  145


## Задание 10. Системы линейных уравнений 

Решите систему линейных уравнений вида: 
$
\begin{cases}
2x + 3y - z = 5 \\
4x - y + 2x = 6 \\
-3x + 5y + 4z = -2
\end{cases}
$

Используйте матричное представление AX = B, где А - матрица коэффициентов, х - вектор неизвестных, В - вектор правой части. Решите систему с помощью np.linalg.solve и выведите результат

In [525]:
A = np.array([[2,3,-1],
             [4,-1,2],
             [-3,5,4]])
B = np.array([[5],[6],[-2]])
print("Ответ:\n",np.linalg.solve(A,B))

Ответ:
 [[1.63963964]
 [0.57657658]
 [0.00900901]]


## Индивидуальное задание.

Задание предусматривает построение СЛУ. Решите полученную СУ с использованием библиотеки NumPy. <br>Для решения системы используйте **метод Крамера** и **матричный метод**. Сравните полученные результаты, с результатами, полученными с помощью **np.linalg.solve**.

**Вариант 12**.<br>
На концерт продано 500 билетов трех категорий: cтандартные, премиум и VIP.<br>
Билеты премиум стоят в 1.5 раза дороже стандартных, а VIP — в 2 раза дороже премиум.<br>
Общий доход от продажи составил 600 000 рублей.<br>
Сколько билетов каждого типа было продано, если известно, что стандартных билетов было на 100 больше, чем премиум?